# Generated by Django 2.2.4 on 2020-12-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackingnode',
            name='flavor_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hackingnode',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hackingtool',
            name='flavor_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hackingtool',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
