# Generated by Django 2.2.4 on 2020-12-29 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201228_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackingToolSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.HackingNode')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.HackingTool')),
                ('tool_becomes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciality_of', to='game.HackingTool')),
            ],
        ),
        migrations.CreateModel(
            name='HackingToolPickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.IntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.HackingNode')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.HackingTool')),
            ],
        ),
    ]
