# Generated by Django 2.2.4 on 2021-01-01 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_hackingtoolpickup_hackingtoolspeciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogNode',
            fields=[
                ('short_name', models.TextField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('speaker', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DialogOption',
            fields=[
                ('short_name', models.TextField(max_length=64, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('restriction', models.TextField(blank=True)),
                ('node_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='game.DialogNode')),
                ('node_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.DialogNode')),
            ],
        ),
        migrations.CreateModel(
            name='DialogHack',
            fields=[
                ('dialognode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.DialogNode')),
                ('hacking_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.HackingNode')),
            ],
            bases=('game.dialognode',),
        ),
    ]
