# Generated by Django 2.2.4 on 2021-01-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_dialoghack_dialognode_dialogoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialognode',
            name='short_name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dialogoption',
            name='short_name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
