# Generated by Django 2.2.4 on 2021-01-01 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210101_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogHackOption',
            fields=[
                ('short_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('restriction', models.TextField(blank=True)),
                ('node_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hacking_options', to='game.DialogNode')),
                ('node_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.HackingNode')),
            ],
        ),
        migrations.DeleteModel(
            name='DialogHack',
        ),
    ]
