# Generated by Django 3.2.8 on 2021-10-20 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210101_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialoghackoption',
            name='node_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hack_options', to='game.dialognode'),
        ),
        migrations.CreateModel(
            name='DialogHackExitOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caught', models.BooleanField()),
                ('restriction', models.TextField(blank=True)),
                ('node_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.dialognode')),
                ('option_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_options', to='game.dialoghackoption')),
            ],
        ),
    ]
